language: node_js

services:
  - docker

node_js:
  - '8'
cache:
  directories:
    - node_modules
script:
  - 'docker build -t ${TRAVIS_REPO_SLUG} .'
  - npm test
  #- codecov
install:
  - npm install
  #- npm install -g codecov
after_success:
  - travis/publish.sh
  - travis/deploy-gh-pages.sh
